apiVersion: v1
kind: Service
metadata:
  labels:
    app: open-podcast-apiserver
  name: open-podcast-apiserver
  namespace: osf2f-system
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: front
      port: 8000
      protocol: TCP
      targetPort: 8000
      nodePort: 32007
  selector:
    control-plane: apiserver
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
